* report z_j_6_4_3_scren.

PROCESS BEFORE OUTPUT.
* MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
* MODULE USER_COMMAND_0100.

MODULE USER_COMMAND_0100.
MODULE CANCEL AT EXIT-COMMAND.



* * notes:
* " 6.5.1 顺序执行逻辑流
* " 系统是按照逻辑流的顺序执行的，例如下面的逻辑流（PAI）：
* PROCESS AFTER INPUT。
* MODULE USER_COMMAND_TEST.
* MODULE CANCELATEXIT-COMMAND.
* MODULE USER_COMMAND_0100.
* " 如果单击退出键，那么“MODULE USER_COMMAND_0100”是不会执行的。
