CREATE DATABASE XSBOOK3
	ON 
		(NAME='XSBOOK3_Data',
		FILENAME='F:\SQL_DATA\XSBOOK3.MDF',
		SIZE=4MB,
		MAXSIZE=20MB,
		FILEGROWTH=10%)
	LOG ON
		(NAME='XSBOOK3_LoG',
		FILENAME='F:\SQL_DATA\XSBOOK3_LOG.LDF',
		SIZE=2MB,
		MAXSIZE=10MB,	
		FILEGROWTH=10%)
GO